### ISSUE TITLE
Uygulama ikonu

### ISSUE THREAD

**Issue by eabay** [Turkcell/gy-phonegap-build#4]
Application JSON (#1)  içinde uygulama ikonunu almak mümkün müdür?

**Comment by capacman** [comment]
Linkini degilmi? Farkli buildler icin farkli iconlar hazirliyo ama ben roota konan dosyayi alirim.

**Comment by eabay** [comment]
https://build.phonegap.com/docs/config-xml

Burada **Icon Support** bölümünde açıklamışlar. Önce root'dan, yoksa da <icon/> tag'lerinden diye.

Phonegap Build muhtemelen olası en büyük ebattaki ikonu alıp onu kendi istediği bir boyuta küçültüyor.

**Comment by capacman** [comment]
cordova kendisi icon support sağlamıyor henüz. Yani burda phohegap build servisi kendisi birşeyler yapıyor. Şimdilik ben url olarak içerde belirtilmiş olan iconu dönücem ama build edilmiş olan dosya gerçek anlamda icon göstermiycek. Biz proda çıkana kadar düzelirse onu kullanırız düzelmezse bir hook scripti yazıp aynı supportu bizim vermemiz gerekicek

**Comment by capacman** [comment]
https://issues.apache.org/jira/browse/CB-2606

**Comment by capacman** [comment]
uygulama iconu linkide şu anda geliyo eğer böyle bir link göremezsen ilgili uygulama kendine bir icon seçmemiş demek bu durumda default bir icon kullanmamız gerekicek oda cordovanın default iconu olur.
