### ISSUE TITLE
Sunucu 404 dönüyor

### ISSUE THREAD

**Issue by eabay** [Turkcell/gy-phonegap-build#5]
162.13.112.150:8080 sürekli olarak 404 dönüyor.

IP ping'e yanıt veriyor.
#2'yi çözüp lokalde çalıştırsam?

**Comment by capacman** [comment]
yeniden bir dene

**Comment by eabay** [comment]
cevap veriyor, eyvallah.

kullanıcılar uçtu ama di mi? :)
