### ISSUE TITLE
QR kod adresi 403 dönüyor

### ISSUE THREAD

**Issue by eabay** [Turkcell/gy-phonegap-build#7]
QR kod telefondan okutulup girilirse http 403 dönüyor.

Oturum açılmış adresten girilirse de:

**_Adres:**_

> http://162.13.112.150:8080/application/1/install?qrKey=v2ka4dt09mui7njq0i353gbgaj

**_QR kod:**_
![](http://i.imgur.com/kt8ADJe.jpg)

**_Cevap:**_

```
may not be empty (path = ApplicationResource.getWithQrKey.arg1, invalidValue = null)
```

**Comment by eabay** [comment]
Bu arada bence şimdilik QR kod özelliğini kapatabiliriz.

**Comment by capacman** [comment]
Ha evet 403 doner henuz calismaz dedigim oydu zaten ordan authenticationu
kaldirmam lazim
